/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-06-13 23:40:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class master_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private javax.servlet.jsp.tagext.JspFragment scripts_css;
  private javax.servlet.jsp.tagext.JspFragment scripts_js_page_level_plugins;
  private javax.servlet.jsp.tagext.JspFragment scripts_js_page_level_scripts;

  public javax.servlet.jsp.tagext.JspFragment getScripts_css() {
    return this.scripts_css;
  }

  public void setScripts_css(javax.servlet.jsp.tagext.JspFragment scripts_css) {
    this.scripts_css = scripts_css;
    jspContext.setAttribute("scripts_css", scripts_css);
  }

  public javax.servlet.jsp.tagext.JspFragment getScripts_js_page_level_plugins() {
    return this.scripts_js_page_level_plugins;
  }

  public void setScripts_js_page_level_plugins(javax.servlet.jsp.tagext.JspFragment scripts_js_page_level_plugins) {
    this.scripts_js_page_level_plugins = scripts_js_page_level_plugins;
    jspContext.setAttribute("scripts_js_page_level_plugins", scripts_js_page_level_plugins);
  }

  public javax.servlet.jsp.tagext.JspFragment getScripts_js_page_level_scripts() {
    return this.scripts_js_page_level_scripts;
  }

  public void setScripts_js_page_level_scripts(javax.servlet.jsp.tagext.JspFragment scripts_js_page_level_scripts) {
    this.scripts_js_page_level_scripts = scripts_js_page_level_scripts;
    jspContext.setAttribute("scripts_js_page_level_scripts", scripts_js_page_level_scripts);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getScripts_css() != null ) 
      _jspx_page_context.setAttribute("scripts_css", getScripts_css());
    if( getScripts_js_page_level_plugins() != null ) 
      _jspx_page_context.setAttribute("scripts_js_page_level_plugins", getScripts_js_page_level_plugins());
    if( getScripts_js_page_level_scripts() != null ) 
      _jspx_page_context.setAttribute("scripts_js_page_level_scripts", getScripts_js_page_level_scripts());

    try {
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!-- \n");
      out.write("Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7\n");
      out.write("Version: 4.7.5\n");
      out.write("Author: KeenThemes\n");
      out.write("Website: http://www.keenthemes.com/\n");
      out.write("Contact: support@keenthemes.com\n");
      out.write("Follow: www.twitter.com/keenthemes\n");
      out.write("Dribbble: www.dribbble.com/keenthemes\n");
      out.write("Like: www.facebook.com/keenthemes\n");
      out.write("Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes\n");
      out.write("Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes\n");
      out.write("License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.\n");
      out.write("-->\n");
      out.write("<!--[if IE 8]> <html lang=\"en\" class=\"ie8 no-js\"> <![endif]-->\n");
      out.write("<!--[if IE 9]> <html lang=\"en\" class=\"ie9 no-js\"> <![endif]-->\n");
      out.write("<!--[if !IE]><!-->\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <!--<![endif]-->\n");
      out.write("    <!-- BEGIN HEAD -->\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <title>Metronic Admin Theme #1 | Admin Dashboard</title>\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\n");
      out.write("        <meta content=\"Preview page of Metronic Admin Theme #1 for statistics, charts, recent events and reports\" name=\"description\" />\n");
      out.write("        <meta content=\"\" name=\"author\" />\n");
      out.write("        <!-- BEGIN GLOBAL MANDATORY STYLES -->\n");
      out.write("        <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/global/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/global/plugins/simple-line-icons/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/global/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- END GLOBAL MANDATORY STYLES -->\n");
      out.write("        <!-- BEGIN PAGE LEVEL PLUGINS -->\n");
      out.write("       \n");
      out.write("       ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getScripts_css() != null) {
        getScripts_css().invoke(_jspx_sout);
      }
      out.write("\n");
      out.write("       \n");
      out.write("        <!-- END PAGE LEVEL PLUGINS -->\n");
      out.write("        <!-- BEGIN THEME GLOBAL STYLES -->\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/global/css/components.min.css\" rel=\"stylesheet\" id=\"style_components\" type=\"text/css\" />\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/global/css/components-rounded.min.css\" rel=\"stylesheet\" id=\"style_components\" type=\"text/css\">\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/global/css/plugins.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- END THEME GLOBAL STYLES -->\n");
      out.write("        <!-- BEGIN THEME LAYOUT STYLES -->\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/layouts/layout/css/layout.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/layouts/layout/css/themes/darkblue.min.css\" rel=\"stylesheet\" type=\"text/css\" id=\"style_color\" />\n");
      out.write("        <link href=\"/DashboardSpringMVC/assets/layouts/layout/css/custom.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- END THEME LAYOUT STYLES -->\n");
      out.write("        <link rel=\"shortcut icon\" href=\"favicon.ico\" /> </head>\n");
      out.write("    <!-- END HEAD -->\n");
      out.write("\n");
      out.write("    <body class=\"page-header-fixed page-sidebar-closed-hide-logo page-content-white\">\n");
      out.write("        <div class=\"page-wrapper\">\n");
      out.write("            <!-- BEGIN HEADER -->\n");
      out.write("            <div class=\"page-header navbar navbar-fixed-top\">\n");
      out.write("                <!-- BEGIN HEADER INNER -->\n");
      out.write("                <div class=\"page-header-inner \">\n");
      out.write("                    <!-- BEGIN LOGO -->\n");
      out.write("                    <div class=\"page-logo\">\n");
      out.write("                        <a href=\"index.html\">\n");
      out.write("                            <img src=\"/DashboardSpringMVC/assets/layouts/layout/img/logo.png\" alt=\"logo\" class=\"logo-default\" /> </a>\n");
      out.write("                        <div class=\"menu-toggler sidebar-toggler\">\n");
      out.write("                            <span></span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- END LOGO -->\n");
      out.write("                    <!-- BEGIN RESPONSIVE MENU TOGGLER -->\n");
      out.write("                    <a href=\"javascript:;\" class=\"menu-toggler responsive-toggler\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                        <span></span>\n");
      out.write("                    </a>\n");
      out.write("                    <!-- END RESPONSIVE MENU TOGGLER -->\n");
      out.write("                    <!-- BEGIN TOP NAVIGATION MENU -->\n");
      out.write("                    <div class=\"top-menu\">\n");
      out.write("                        <ul class=\"nav navbar-nav pull-right\">\n");
      out.write("                            <!-- BEGIN NOTIFICATION DROPDOWN -->\n");
      out.write("                            <!-- DOC: Apply \"dropdown-dark\" class after \"dropdown-extended\" to change the dropdown styte -->\n");
      out.write("                            <!-- DOC: Apply \"dropdown-hoverable\" class after below \"dropdown\" and remove data-toggle=\"dropdown\" data-hover=\"dropdown\" data-close-others=\"true\" attributes to enable hover dropdown mode -->\n");
      out.write("                            <!-- DOC: Remove \"dropdown-hoverable\" and add data-toggle=\"dropdown\" data-hover=\"dropdown\" data-close-others=\"true\" attributes to the below A element with dropdown-toggle class -->\n");
      out.write("                            <!-- END NOTIFICATION DROPDOWN -->\n");
      out.write("                            <!-- BEGIN INBOX DROPDOWN -->\n");
      out.write("                            <!-- DOC: Apply \"dropdown-dark\" class after below \"dropdown-extended\" to change the dropdown styte -->\n");
      out.write("                            <!-- END INBOX DROPDOWN -->\n");
      out.write("                            <!-- BEGIN TODO DROPDOWN -->\n");
      out.write("                            <!-- DOC: Apply \"dropdown-dark\" class after below \"dropdown-extended\" to change the dropdown styte -->\n");
      out.write("                            <!-- END TODO DROPDOWN -->\n");
      out.write("                            <!-- BEGIN USER LOGIN DROPDOWN -->\n");
      out.write("                            <!-- DOC: Apply \"dropdown-dark\" class after below \"dropdown-extended\" to change the dropdown styte -->\n");
      out.write("                            <li class=\"dropdown dropdown-user\">\n");
      out.write("                                <a href=\"javascript:;\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-close-others=\"true\">\n");
      out.write("                                    <img alt=\"\" class=\"img-circle\" src=\"/DashboardSpringMVC/assets/layouts/layout/img/avatar3_small.jpg\" />\n");
      out.write("                                    <span class=\"username username-hide-on-mobile\"> ");
out.print(request.getSession().getAttribute("usuarioLogado")); 
      out.write("</span>\n");
      out.write("                                    <i class=\"fa fa-angle-down\"></i>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"dropdown-menu dropdown-menu-default\">\n");
      out.write("                                    \n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"/DashboardSpringMVC/sistema/logout\">\n");
      out.write("                                            <i class=\"icon-key\"></i> Sair </a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <!-- END USER LOGIN DROPDOWN -->\n");
      out.write("                            <!-- BEGIN QUICK SIDEBAR TOGGLER -->\n");
      out.write("                            <!-- DOC: Apply \"dropdown-dark\" class after below \"dropdown-extended\" to change the dropdown styte -->\n");
      out.write("                           \n");
      out.write("                            <!-- END QUICK SIDEBAR TOGGLER -->\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- END TOP NAVIGATION MENU -->\n");
      out.write("                </div>\n");
      out.write("                <!-- END HEADER INNER -->\n");
      out.write("            </div>\n");
      out.write("            <!-- END HEADER -->\n");
      out.write("            <!-- BEGIN HEADER & CONTENT DIVIDER -->\n");
      out.write("            <div class=\"clearfix\"> </div>\n");
      out.write("            <!-- END HEADER & CONTENT DIVIDER -->\n");
      out.write("            <!-- BEGIN CONTAINER -->\n");
      out.write("            <div class=\"page-container\">\n");
      out.write("                <!-- BEGIN SIDEBAR -->\n");
      out.write("                <div class=\"page-sidebar-wrapper\">\n");
      out.write("                    <!-- BEGIN SIDEBAR -->\n");
      out.write("                    <!-- DOC: Set data-auto-scroll=\"false\" to disable the sidebar from auto scrolling/focusing -->\n");
      out.write("                    <!-- DOC: Change data-auto-speed=\"200\" to adjust the sub menu slide up/down speed -->\n");
      out.write("                    <div class=\"page-sidebar navbar-collapse collapse\">\n");
      out.write("                        <!-- BEGIN SIDEBAR MENU -->\n");
      out.write("                        <!-- DOC: Apply \"page-sidebar-menu-light\" class right after \"page-sidebar-menu\" to enable light sidebar menu style(without borders) -->\n");
      out.write("                        <!-- DOC: Apply \"page-sidebar-menu-hover-submenu\" class right after \"page-sidebar-menu\" to enable hoverable(hover vs accordion) sub menu mode -->\n");
      out.write("                        <!-- DOC: Apply \"page-sidebar-menu-closed\" class right after \"page-sidebar-menu\" to collapse(\"page-sidebar-closed\" class must be applied to the body element) the sidebar sub menu mode -->\n");
      out.write("                        <!-- DOC: Set data-auto-scroll=\"false\" to disable the sidebar from auto scrolling/focusing -->\n");
      out.write("                        <!-- DOC: Set data-keep-expand=\"true\" to keep the submenues expanded -->\n");
      out.write("                        <!-- DOC: Set data-auto-speed=\"200\" to adjust the sub menu slide up/down speed -->\n");
      out.write("                        <ul class=\"page-sidebar-menu  page-header-fixed \" data-keep-expanded=\"false\" data-auto-scroll=\"true\" data-slide-speed=\"200\" style=\"padding-top: 20px\">\n");
      out.write("                            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below \"sidebar-toggler-wrapper\" LI element -->\n");
      out.write("                            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->\n");
      out.write("                            <li class=\"sidebar-toggler-wrapper hide\">\n");
      out.write("                                <div class=\"sidebar-toggler\">\n");
      out.write("                                    <span></span>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <!-- END SIDEBAR TOGGLER BUTTON -->\n");
      out.write("                            <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below \"sidebar-search-wrapper\" LI element -->\n");
      out.write("                            <li class=\"sidebar-search-wrapper\">\n");
      out.write("                                <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->\n");
      out.write("                                <!-- DOC: Apply \"sidebar-search-bordered\" class the below search form to have bordered search box -->\n");
      out.write("                                <!-- DOC: Apply \"sidebar-search-bordered sidebar-search-solid\" class the below search form to have bordered & solid search box -->\n");
      out.write("                                <form class=\"sidebar-search  \" action=\"page_general_search_3.html\" method=\"POST\">\n");
      out.write("                                    <a href=\"javascript:;\" class=\"remove\">\n");
      out.write("                                        <i class=\"icon-close\"></i>\n");
      out.write("                                    </a>\n");
      out.write("                                    <div class=\"input-group\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\n");
      out.write("                                        <span class=\"input-group-btn\">\n");
      out.write("                                            <a href=\"javascript:;\" class=\"btn submit\">\n");
      out.write("                                                <i class=\"icon-magnifier\"></i>\n");
      out.write("                                            </a>\n");
      out.write("                                        </span>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                                <!-- END RESPONSIVE QUICK SEARCH FORM -->\n");
      out.write("                            </li>\n");
      out.write("                            <li id=\"dashboardli\" class=\"nav-item start\">\n");
      out.write("                                <a href=\"javascript:;\" class=\"nav-link nav-toggle\">\n");
      out.write("                                    <i class=\"icon-home\"></i>\n");
      out.write("                                    <span class=\"title\">Dashboard</span>\n");
      out.write("                                    <span class=\"selected\"></span>\n");
      out.write("                                    <span class=\"arrow open\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sub-menu\">\n");
      out.write("                                    <li id=\"dashboard_li_index\" class=\"nav-item start\">\n");
      out.write("                                        <a href=\"/DashboardSpringMVC/dashboard/index\" class=\"nav-link \">\n");
      out.write("                                            <i class=\"icon-bar-chart\"></i>\n");
      out.write("                                            <span class=\"title\">Index</span>\n");
      out.write("                                            <span class=\"selected\"></span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                   \n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                             <li id=\"consulta_produto\" class=\"nav-item start\">\n");
      out.write("                                        <a href=\"/DashboardSpringMVC/Produto/Consulta\" class=\"nav-link \">\n");
      out.write("                                            <i class=\"icon-bar-chart\"></i>\n");
      out.write("                                            <span class=\"title\">Produto</span>\n");
      out.write("                                            <span class=\"selected\"></span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                            <li id=\"usuarioli\" class=\"nav-item start\">\n");
      out.write("                                <a href=\"javascript:;\" class=\"nav-link nav-toggle\">\n");
      out.write("                                    <i class=\"icon-user\"></i>\n");
      out.write("                                    <span class=\"title\">Usuario</span>\n");
      out.write("                                    <span class=\"selected\"></span>\n");
      out.write("                                    <span class=\"arrow open\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"sub-menu\">\n");
      out.write("                                    <li id=\"usuario_li_consulta\" class=\"nav-item start\">\n");
      out.write("                                        <a href=\"/DashboardSpringMVC/Usuario/Consulta\" class=\"nav-link \">\n");
      out.write("                                            <i class=\"icon-user\"></i>\n");
      out.write("                                            <span class=\"title\">Usuario</span>\n");
      out.write("                                            <span class=\"selected\"></span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li id=\"controle_acesso_li_consulta\" class=\"nav-item start\">\n");
      out.write("                                        <a href=\"/DashboardSpringMVC/ControleAcesso/Consulta\" class=\"nav-link \">\n");
      out.write("                                            <i class=\"icon-lock\"></i>\n");
      out.write("                                            <span class=\"title\">Controle Acesso</span>\n");
      out.write("                                            <span class=\"selected\"></span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                   \n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                              </ul>\n");
      out.write("                        <!-- END SIDEBAR MENU -->\n");
      out.write("                        <!-- END SIDEBAR MENU -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- END SIDEBAR -->\n");
      out.write("                </div>\n");
      out.write("                <!-- END SIDEBAR -->\n");
      out.write("                <!-- BEGIN CONTENT -->\n");
      out.write("                <div class=\"page-content-wrapper\">\n");
      out.write("                    <!-- BEGIN CONTENT BODY -->\n");
      out.write("                    <div class=\"page-content\">\n");
      out.write("                        <!-- BEGIN PAGE HEADER-->\n");
      out.write("                        <!-- BEGIN THEME PANEL -->\n");
      out.write("                        <div class=\"theme-panel hidden-xs hidden-sm\">\n");
      out.write("                            <div class=\"toggler\"> </div>\n");
      out.write("                            <div class=\"toggler-close\"> </div>\n");
      out.write("                            <div class=\"theme-options\">\n");
      out.write("                                <div class=\"theme-option theme-colors clearfix\">\n");
      out.write("                                    <span> THEME COLOR </span>\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li class=\"color-default current tooltips\" data-style=\"default\" data-container=\"body\" data-original-title=\"Default\"> </li>\n");
      out.write("                                        <li class=\"color-darkblue tooltips\" data-style=\"darkblue\" data-container=\"body\" data-original-title=\"Dark Blue\"> </li>\n");
      out.write("                                        <li class=\"color-blue tooltips\" data-style=\"blue\" data-container=\"body\" data-original-title=\"Blue\"> </li>\n");
      out.write("                                        <li class=\"color-grey tooltips\" data-style=\"grey\" data-container=\"body\" data-original-title=\"Grey\"> </li>\n");
      out.write("                                        <li class=\"color-light tooltips\" data-style=\"light\" data-container=\"body\" data-original-title=\"Light\"> </li>\n");
      out.write("                                        <li class=\"color-light2 tooltips\" data-style=\"light2\" data-container=\"body\" data-html=\"true\" data-original-title=\"Light 2\"> </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Theme Style </span>\n");
      out.write("                                    <select class=\"layout-style-option form-control input-sm\">\n");
      out.write("                                        <option value=\"square\" selected=\"selected\">Square corners</option>\n");
      out.write("                                        <option value=\"rounded\">Rounded corners</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Layout </span>\n");
      out.write("                                    <select class=\"layout-option form-control input-sm\">\n");
      out.write("                                        <option value=\"fluid\" selected=\"selected\">Fluid</option>\n");
      out.write("                                        <option value=\"boxed\">Boxed</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Header </span>\n");
      out.write("                                    <select class=\"page-header-option form-control input-sm\">\n");
      out.write("                                        <option value=\"fixed\" selected=\"selected\">Fixed</option>\n");
      out.write("                                        <option value=\"default\">Default</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Top Menu Dropdown</span>\n");
      out.write("                                    <select class=\"page-header-top-dropdown-style-option form-control input-sm\">\n");
      out.write("                                        <option value=\"light\" selected=\"selected\">Light</option>\n");
      out.write("                                        <option value=\"dark\">Dark</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Sidebar Mode</span>\n");
      out.write("                                    <select class=\"sidebar-option form-control input-sm\">\n");
      out.write("                                        <option value=\"fixed\">Fixed</option>\n");
      out.write("                                        <option value=\"default\" selected=\"selected\">Default</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Sidebar Menu </span>\n");
      out.write("                                    <select class=\"sidebar-menu-option form-control input-sm\">\n");
      out.write("                                        <option value=\"accordion\" selected=\"selected\">Accordion</option>\n");
      out.write("                                        <option value=\"hover\">Hover</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Sidebar Style </span>\n");
      out.write("                                    <select class=\"sidebar-style-option form-control input-sm\">\n");
      out.write("                                        <option value=\"default\" selected=\"selected\">Default</option>\n");
      out.write("                                        <option value=\"light\">Light</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Sidebar Position </span>\n");
      out.write("                                    <select class=\"sidebar-pos-option form-control input-sm\">\n");
      out.write("                                        <option value=\"left\" selected=\"selected\">Left</option>\n");
      out.write("                                        <option value=\"right\">Right</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"theme-option\">\n");
      out.write("                                    <span> Footer </span>\n");
      out.write("                                    <select class=\"page-footer-option form-control input-sm\">\n");
      out.write("                                        <option value=\"fixed\">Fixed</option>\n");
      out.write("                                        <option value=\"default\" selected=\"selected\">Default</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- END THEME PANEL -->\n");
      out.write("                        <!-- BEGIN PAGE BAR --> \n");
      out.write("\n");
      out.write("                            ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getJspBody() != null)
        getJspBody().invoke(_jspx_sout);
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,getJspContext());
      out.write("\n");
      out.write("                        \t\n");
      out.write("                        <!-- END DASHBOARD STATS 1-->\n");
      out.write("                 <!-- END CONTAINER -->\n");
      out.write("            <!-- BEGIN FOOTER -->\n");
      out.write("            </div></div></div>\n");
      out.write("            <div class=\"page-footer\">\n");
      out.write("                <div class=\"page-footer-inner\"> 2016 &copy; Metronic Theme By\n");
      out.write("                    <a target=\"_blank\" href=\"http://keenthemes.com\">Keenthemes</a> &nbsp;|&nbsp;\n");
      out.write("                    <a href=\"http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes\" title=\"Purchase Metronic just for 27$ and get lifetime updates for free\" target=\"_blank\">Purchase Metronic!</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"scroll-to-top\">\n");
      out.write("                    <i class=\"icon-arrow-up\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- END FOOTER -->\n");
      out.write("        </div>\n");
      out.write("        <!-- BEGIN QUICK NAV -->\n");
      out.write("         <!-- END QUICK NAV -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("<script src=\"/DashboardSpringMVC/assets/global/plugins/respond.min.js\"></script>\n");
      out.write("<script src=\"/DashboardSpringMVC/assets/global/plugins/excanvas.min.js\"></script> \n");
      out.write("<script src=\"/DashboardSpringMVC/assets/global/plugins/ie8.fix.min.js\"></script> \n");
      out.write("<![endif]-->\n");
      out.write("        <!-- BEGIN CORE PLUGINS -->\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/global/plugins/jquery.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/global/plugins/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/global/plugins/js.cookie.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/global/plugins/jquery.blockui.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- END CORE PLUGINS -->\n");
      out.write("        <!-- BEGIN PAGE LEVEL PLUGINS -->\n");
      out.write("       ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getScripts_js_page_level_plugins() != null) {
        getScripts_js_page_level_plugins().invoke(_jspx_sout);
      }
      out.write("\n");
      out.write("        <!-- END PAGE LEVEL PLUGINS -->\n");
      out.write("        <!-- BEGIN THEME GLOBAL SCRIPTS -->\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/global/scripts/app.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- END THEME GLOBAL SCRIPTS -->\n");
      out.write("        <!-- BEGIN PAGE LEVEL SCRIPTS -->\n");
      out.write("        ");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getScripts_js_page_level_scripts() != null) {
        getScripts_js_page_level_scripts().invoke(_jspx_sout);
      }
      out.write("\n");
      out.write("        <!-- END PAGE LEVEL SCRIPTS -->\n");
      out.write("        <!-- BEGIN THEME LAYOUT SCRIPTS -->\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/layouts/layout/scripts/layout.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/layouts/layout/scripts/demo.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/layouts/global/scripts/quick-sidebar.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/DashboardSpringMVC/assets/layouts/global/scripts/quick-nav.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- END THEME LAYOUT SCRIPTS -->\n");
      out.write("        <script>\n");
      out.write("            $(document).ready(function()\n");
      out.write("            {\n");
      out.write("                $('#clickmewow').click(function()\n");
      out.write("                {\n");
      out.write("                    $('#radio1003').attr('checked', 'checked');\n");
      out.write("                });\n");
      out.write("            })\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
